FROM eclipse-temurin:11-jdk-jammy

ENV SPARK_VERSION=3.5.1
ENV HADOOP_VERSION=3

RUN apt-get update && apt-get install -y curl python3 python3-pip

# Install Jupyter + helpers
RUN pip3 install notebook pandas matplotlib

RUN pip install psycopg2-binary

RUN curl -fLo spark.tgz https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz

RUN tar -xzf spark.tgz

RUN mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} /opt/spark

RUN rm spark.tgz

# Add Kafka connector dependencies (ALL required ones)

RUN curl -L -o /opt/spark/jars/spark-sql-kafka.jar \
https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.1/spark-sql-kafka-0-10_2.12-3.5.1.jar && \

curl -L -o /opt/spark/jars/spark-token-provider-kafka.jar \
https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.1/spark-token-provider-kafka-0-10_2.12-3.5.1.jar && \

curl -L -o /opt/spark/jars/kafka-clients.jar \
https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.5.1/kafka-clients-3.5.1.jar && \

curl -L -o /opt/spark/jars/commons-pool2.jar \
https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar && \

# S3 / MinIO support
curl -L -o /opt/spark/jars/hadoop-aws.jar \
https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar && \

curl -L -o /opt/spark/jars/aws-sdk.jar \
https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar && \

curl -L -o /opt/spark/jars/postgresql.jar \
https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.3/postgresql-42.7.3.jar && \

curl -L -o /opt/spark/jars/hadoop-common.jar \
https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-common/3.3.4/hadoop-common-3.3.4.jar && \

curl -L -o /opt/spark/jars/delta-spark.jar \
https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar && \

curl -L -o /opt/spark/jars/delta-storage.jar \
https://repo1.maven.org/maven2/io/delta/delta-storage/3.1.0/delta-storage-3.1.0.jar && \

curl -L -o /opt/spark/jars/antlr4-runtime.jar \
https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.9.3/antlr4-runtime-4.9.3.jar

ENV SPARK_HOME=/opt/spark
ENV PYTHONPATH=/opt/spark/python:/opt/spark/python/lib/py4j-0.10.9.7-src.zip
ENV PATH=$SPARK_HOME/bin:$PATH

ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3
ENV AWS_REGION=us-east-1